### ISSUE TITLE
existdb-sync task breaks if workspace path contains a space

### ISSUE THREAD

**Issue by joewiz** [wolfgangmm/existdb-langserver#8]
When testing the vscode extension, I noticed that the existdb-sync task would fail if the path to the workspace contains a space. 

The error:

> > Executing task in folder air table: node /Users/joe/.vscode/extensions/exist-db.existdb-vscode-1.0.2/sync/dist/sync.js -s http://localhost:8080/exist -u admin -p   -c /db/apps/airtable /Users/joe/Downloads/air table -i ".existdb.json" ".git/**" "node_modules/**" "bower_components/**" <
> 
> directory /Users/joe/Downloads/air not found
> The terminal process terminated with exit code: 1
> 
> Terminal will be reused by tasks, press any key to close it.

The path in question is `/Users/joe/Downloads/air table`. 

If I wrap the path in quotes or escape the space (e.g., `"/Users/joe/Downloads/air table"` or `/Users/joe/Downloads/air\ table`) and run the command again, it succeeds. However, I can't figure out how to get vscode to add quotes or escape the space.

Could anyone suggest a method that might work? I think the relevant code is here: https://github.com/wolfgangmm/existdb-langserver/blob/3eccea86d7b6123f6d245256b64005379d86959c/sync/src/sync.ts#L105-L121

**Comment by wolfgangmm** [comment]
I think we would need to change the code which constructs the command line: https://github.com/wolfgangmm/existdb-langserver/blob/3eccea86d7b6123f6d245256b64005379d86959c/client/src/task-provider.ts#L71 to add quotes around the `-c` parameter.

**Comment by joewiz** [comment]
@wolfgangmm I can confirm that wrapping `${folder.uri.fsPath}` in double quotes fixes the problem. Here's sample output from the Build Task showing the quotes working - or so it appears to me. 

> \> Executing task in folder airtable: node /Users/joe/workspace/existdb-langserver/sync/dist/sync.js -s http://localhost:8080/exist -u admin -p   -c /db/apps/airtable "/Users/joe/Library/Mobile Documents/iCloud~co~noteplan~NotePlan/Documents/Notes/airtable" -i ".existdb.json" ".git/**" "node_modules/**" "bower_components/**" <
> 
> Watching /Users/joe/Library/Mobile Documents/iCloud~co~noteplan~NotePlan/Documents/Notes/airtable
Using fs events.

Can you confirm that this "Watching... Using fs events" is what you'd expect to see with the vscode plugin?

**Comment by wolfgangmm** [comment]
@joewiz yes, the output appears to be right.
